export const ClienteleTableData = [
  {
    id: 1,
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 2,
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 3,
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 4,
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 5,
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 6,
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 7,
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 8,
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 9,
    businessname: "PursBusiness",
    type: "NGO",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
  {
    id: 10,
    businessname: "VoltWolf",
    type: "Enterprise",
    account: "1234567890",
    email: "yourmail@gmail.com",
  },
];
